# Config file for automatic testing at travis-ci.org

dist: xenial  # For Python 3.7
language: python
services:
    - docker
python:
  - 3.8-dev
  - 3.7
  - 3.6

before_install:
    - docker build -t winsign .
    - docker run winsign /bin/sh -c "tox"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
